export const ACTION_TYPES = {
    SET_USER_LOGGED_IN: "SET_USER_LOGGED_IN",
    SET_USER_LOGGED_OUT: "SET_USER_LOGGED_OUT",
    SET_USER_REGISTERED: "SET_USER_REGISTERED",
    SET_USER_CREDENTIALS: "SET_USER",
}